# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Marca', models.CharField(max_length=50)),
                ('Longitud', models.IntegerField()),
                ('Color', models.CharField(max_length=30)),
                ('Estilo', models.CharField(max_length=50)),
                ('Aviable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Esquis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Marca', models.CharField(max_length=50)),
                ('Longitud', models.IntegerField()),
                ('Color', models.CharField(max_length=30)),
                ('Estilo', models.CharField(max_length=50)),
                ('Aviable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('User_Name', models.CharField(max_length=50)),
                ('Passwd', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
