# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Longitud', models.IntegerField()),
                ('Color', models.CharField(max_length=30)),
                ('Estilo', models.CharField(max_length=50)),
                ('Aviable', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Botas',
        ),
        migrations.DeleteModel(
            name='Esquis',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='ID',
            new_name='Clave',
        ),
    ]
